name: PingTab
main: br.net.hexafun.PingTab.PingTab
version: 1.5
authors: [tiagoratto]
commands:
  pingtab:
    description: Manages the PingTab plugin.
    usage: /pingtab [reload]
    permission: pingtab.reload
    permission-message: You don't have permission
  ping:
    description: Ping yourself or a player, also you can list players and their's pings
    usage: /ping [none|player|list]
    permission: pingtab.ping
    permission-message: You don't have permission
permissions:
  pingtab.*:
    description: Gives access to all pingtab features
    children:
      pingtab.showscoreboard: true
      pingtab.ping: true
  pingtab.showscoreboard:
    description: Allow a user to show the PingTab scoreboard
    default: true
  pingtab.ping:
    description: Ping a player or yourself
    default: true
  pingtab.reload:
    description: Reload the plugin configuration
    default: op